### ISSUE TITLE
whatsapp-web cli starts Chrome and – after phone conn. – crashes it

### ISSUE THREAD

**Issue by tomasi-o** [zvovov/whatsapp-web#14]
I have to reopen this issue, as with a new version of Chrome (Version 64.0.3282.186 (official build) (64-Bit)) and the appropriate chromedriver version (ChromeDriver 2.35) whatsapp-web cli crashes after taking these steps:

    iMac:whatsapp-web _username_$ python chat.py _WhatsappUser_

    (Google Chrome is started, loggin into whatsapp-web capturing the code on the Webpage /w my smartphone)

    my Terminal asks: Phone connected? y/n:

    As soon as I type in 'y', Google Chrome crashes and I get this error message:

```
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/header//div[contains(@Class, "chat-main")]"}
    (Session info: chrome=64.0.3282.186)
    (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.11.6 x86_64)

    Chromedriver Error. Read the above error (if any), then
    Check if installed chromedriver version is compatible with installed Chrome vesion.
```

**The path in chat.py which points to the location of the chromedriver binary file is correct, although the installed versions of python and selenium differ:**
Python 3.6.4
selenium 3.4.0 (which is the selenium version which gets installed after using the pip install command)

Maybe you can help me out again? Thank you in advance!

**Comment by italogfernandes** [comment]
I'm having the same problem.
:/

**Comment by zvovov** [comment]
Working on a fix. Should be up by the weekend

**Comment by zvovov** [comment]
Whatsapp changed some DOM elements on their website. Should be fixed now.

**Comment by tomasi-o** [comment]
Still not getting it to start up, I am getting the following error (after reinstalling chromedriver using homebrew, setting the PATH of chromedriver (usr/local/bin/chromedriver), and editing the path in chat.py):
`Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

	Chromedriver Error. Read the above error (if any), then
	Check if installed chromedriver version is compatible with installed Chrome version.`

Maybe I did not set the path/to/chromedriver right in chat.py? Below is my try, maybe you can point me to what I did wrong (I am a python noob, btw):
`config = {
 'chromedriver_path': "{0}usr/local/bin/chromedriver".format(os.environ['HOME']),
# 'chromedriver_path': "usr/local/bin/chromedriver".format(os.environ['HOME']),`

**Comment by tomasi-o** [comment]
Finally got it running. To some extent, at least. 

1. Found out that homebrew does not install chromedriver at the path I set, but places a symbolic link instead (MacOS), so I just changed the path to chromedriver in chat.py accordingly.

2. Had to update chromedriver manually to 2.38 (homebrew is still residing at 2.37) to prevent the crash described  here: [https://github.com/zvovov/whatsapp-web/issues/14#issue-301791220](url)

Still I get an error after trying to send the first message after the prompt "Phone connected? y/n, as follows:
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "chat.py", line 119, in startGetMsg
    incoming_scheduler.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "chat.py", line 138, in getMsg
    if first_msg: # if one or more messages exist
UnboundLocalError: local variable 'first_msg' referenced before assignment`

**Comment by tomasi-o** [comment]
Still getting an error after typing some messages without any:
`Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "chat.py", line 122, in startGetMsg
    incoming_scheduler.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "chat.py", line 132, in getMsg
    curr_thread_name = printThreadName(driver)
  File "chat.py", line 225, in printThreadName
    curr_thread_name = driver.find_element(By.XPATH, '//*[@id="main"]/header//span[contains(@dir, "auto")]').text
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 784, in find_element
    'value': value})['value']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1250, in _send_request
    self.putrequest(method, url, **skips)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1108, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent`

**Comment by tomasi-o** [comment]
Dependencies installed:
- selenium 3.4.0
- Python 3.6.8
- ChromeDriver 2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011)
